// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: model/radcheck.proto

package model

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Radcheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Attribute string `protobuf:"bytes,3,opt,name=Attribute,proto3" json:"Attribute,omitempty"`
	OP        string `protobuf:"bytes,4,opt,name=OP,proto3" json:"OP,omitempty"`
	Value     string `protobuf:"bytes,5,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Radcheck) Reset() {
	*x = Radcheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_radcheck_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Radcheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Radcheck) ProtoMessage() {}

func (x *Radcheck) ProtoReflect() protoreflect.Message {
	mi := &file_model_radcheck_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Radcheck.ProtoReflect.Descriptor instead.
func (*Radcheck) Descriptor() ([]byte, []int) {
	return file_model_radcheck_proto_rawDescGZIP(), []int{0}
}

func (x *Radcheck) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Radcheck) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Radcheck) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Radcheck) GetOP() string {
	if x != nil {
		return x.OP
	}
	return ""
}

func (x *Radcheck) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RadcheckList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Radcheck `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RadcheckList) Reset() {
	*x = RadcheckList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_radcheck_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RadcheckList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadcheckList) ProtoMessage() {}

func (x *RadcheckList) ProtoReflect() protoreflect.Message {
	mi := &file_model_radcheck_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadcheckList.ProtoReflect.Descriptor instead.
func (*RadcheckList) Descriptor() ([]byte, []int) {
	return file_model_radcheck_proto_rawDescGZIP(), []int{1}
}

func (x *RadcheckList) GetList() []*Radcheck {
	if x != nil {
		return x.List
	}
	return nil
}

var File_model_radcheck_proto protoreflect.FileDescriptor

var file_model_radcheck_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x72, 0x61, 0x64, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x08, 0x52, 0x61,
	0x64, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x50,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x0c, 0x52, 0x61, 0x64, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x61, 0x64,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xaa, 0x01, 0x0a, 0x09,
	0x52, 0x61, 0x64, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x46, 0x69, 0x6e,
	0x64, 0x12, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x61, 0x64, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x1a, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x61, 0x64, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x04, 0x53, 0x61, 0x76,
	0x65, 0x12, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x61, 0x64, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09,
	0x53, 0x61, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x52, 0x61, 0x64, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_radcheck_proto_rawDescOnce sync.Once
	file_model_radcheck_proto_rawDescData = file_model_radcheck_proto_rawDesc
)

func file_model_radcheck_proto_rawDescGZIP() []byte {
	file_model_radcheck_proto_rawDescOnce.Do(func() {
		file_model_radcheck_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_radcheck_proto_rawDescData)
	})
	return file_model_radcheck_proto_rawDescData
}

var file_model_radcheck_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_radcheck_proto_goTypes = []interface{}{
	(*Radcheck)(nil),     // 0: model.Radcheck
	(*RadcheckList)(nil), // 1: model.RadcheckList
	(*empty.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_model_radcheck_proto_depIdxs = []int32{
	0, // 0: model.RadcheckList.list:type_name -> model.Radcheck
	0, // 1: model.Radchecks.Find:input_type -> model.Radcheck
	0, // 2: model.Radchecks.Save:input_type -> model.Radcheck
	1, // 3: model.Radchecks.SaveBatch:input_type -> model.RadcheckList
	1, // 4: model.Radchecks.Find:output_type -> model.RadcheckList
	2, // 5: model.Radchecks.Save:output_type -> google.protobuf.Empty
	2, // 6: model.Radchecks.SaveBatch:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_radcheck_proto_init() }
func file_model_radcheck_proto_init() {
	if File_model_radcheck_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_radcheck_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Radcheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_radcheck_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RadcheckList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_radcheck_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_radcheck_proto_goTypes,
		DependencyIndexes: file_model_radcheck_proto_depIdxs,
		MessageInfos:      file_model_radcheck_proto_msgTypes,
	}.Build()
	File_model_radcheck_proto = out.File
	file_model_radcheck_proto_rawDesc = nil
	file_model_radcheck_proto_goTypes = nil
	file_model_radcheck_proto_depIdxs = nil
}
